import './globals.css'
import type { Metadata } from 'next'
import { Navbar } from '@/components'
import Provider from './Provider'
export const metadata: Metadata = {
  title: 'E-commerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
            
  children,
}: {
  children: React.ReactNode
}) {
    
  return (
    <html lang="en">

     <body className="relative px-5  max-w-[1280px] mx-auto">
          <Provider>
              <Navbar />
               {children}
          </Provider>
        </body>
    </html>
  )
}
